// Request builder draft types — generated by templates or AI, edited in
// the preview, then turned into a real PhotoBriefRequest on Create.
import type { ContextQuestion, GuideStep, PhotoGuide } from "@/types/photobrief";

export interface ReadinessRule {
  id: string;
  /** Plain-language description ("All required photos captured", etc.) */
  description: string;
  weight: number; // contribution to readiness score 0-100
}

export interface RequestDraft {
  /** Stable id used while editing in the UI. */
  draftId: string;
  /** Source — informs the Save-as-Guide behavior. */
  source: "template" | "ai";
  /** Original prompt if source = "ai". */
  prompt?: string;
  /** Guide id if source = "template", or AI-suggested base. */
  baseGuideId?: string;

  title: string;
  introMessage: string;
  completionMessage: string;
  steps: GuideStep[];
  questions: ContextQuestion[];
  readinessRules: ReadinessRule[];

  recipientName: string;
  recipientContact: string;
}

/** Build a draft from an existing PhotoGuide template. */
export function draftFromGuide(guide: PhotoGuide): RequestDraft {
  return {
    draftId: `draft_${Date.now()}`,
    source: "template",
    baseGuideId: guide.id,
    title: guide.name,
    introMessage: `Hi! I'll walk you through a few photos for your ${guide.category.toLowerCase()} request. Should take about 2 minutes.`,
    completionMessage:
      "Thanks! Your photos are on the way. We'll get back to you shortly.",
    steps: guide.steps.map((s) => ({ ...s })),
    questions: guide.questions.map((q) => ({ ...q })),
    readinessRules: defaultReadinessRules(guide.steps.length),
    recipientName: "",
    recipientContact: "",
  };
}

export function defaultReadinessRules(stepCount: number): ReadinessRule[] {
  return [
    {
      id: "rr_required",
      description: "All required photos captured",
      weight: 60,
    },
    {
      id: "rr_quality",
      description: `At least ${Math.max(1, Math.ceil(stepCount * 0.7))} photos pass AI quality checks`,
      weight: 25,
    },
    {
      id: "rr_questions",
      description: "All required context questions answered",
      weight: 15,
    },
  ];
}
