// Seed guide templates. Adding a new guide = adding an entry here.
// Pages MUST NOT hardcode guides — they read from this config.
//
// Curated metadata (`curatedCategory`, `bestFor`, `estimatedMinutes`,
// `recommendedPlan`, `launchReady`) controls what shows up in the public
// Guide Library. Internal/admin-only templates leave `launchReady = false`
// so they only appear behind the admin toggle. This mirrors the curated
// subset of the PhotoBrief Template Directory workbook.
import type { PhotoGuide } from "@/types/photobrief";

export const guideTemplates: PhotoGuide[] = [
  // ─── Service Quote Intake ──────────────────────────────────────────────
  {
    id: "guide_leak",
    name: "Leak diagnosis intake",
    category: "Plumbing",
    description: "Capture the leak, surrounding area, and shut-off valve so we can quote accurately.",
    isTemplate: true,
    curatedCategory: "service_quote",
    bestFor: "Plumbers quoting urgent leak calls without a site visit.",
    estimatedMinutes: 4,
    recommendedPlan: "free",
    launchReady: true,
    steps: [
      {
        id: "leak_step_1",
        orderIndex: 0,
        title: "Wide shot of the area",
        instructions: "Stand back and capture the whole space around the leak.",
        shotType: "wide",
        overlayType: "full_area",
        aiChecks: ["blur", "low_light", "wide_shot_detected"],
        required: true,
      },
      {
        id: "leak_step_2",
        orderIndex: 1,
        title: "Close-up of the leak",
        instructions: "Get close enough to see exactly where water is coming from.",
        shotType: "close_up",
        overlayType: "close_up",
        aiChecks: ["blur", "damage_visible", "close_up_detected"],
        required: true,
      },
      {
        id: "leak_step_3",
        orderIndex: 2,
        title: "Shut-off valve",
        instructions: "Photo of the nearest shut-off valve so we know what's accessible.",
        shotType: "wide",
        overlayType: "full_area",
        aiChecks: ["blur", "missing_required_item"],
        required: true,
      },
      {
        id: "leak_step_4",
        orderIndex: 3,
        title: "Supply line label",
        instructions: "Straight-on photo of any label or stamp on the supply line.",
        shotType: "label",
        overlayType: "label",
        aiChecks: ["blur", "unreadable_text", "label_detected"],
        required: false,
      },
    ],
    questions: [
      {
        id: "leak_q_1",
        orderIndex: 0,
        prompt: "When did you first notice the leak?",
        inputType: "short_text",
        required: true,
      },
      {
        id: "leak_q_2",
        orderIndex: 1,
        prompt: "Is water actively running right now?",
        inputType: "single_select",
        options: ["Yes", "No", "Slow drip"],
        required: true,
      },
    ],
  },
  {
    id: "guide_water_heater",
    name: "Water heater replacement",
    category: "Plumbing",
    description: "Photos of the unit, model plate, venting, and surrounding clearance.",
    isTemplate: true,
    curatedCategory: "service_quote",
    bestFor: "Quoting tank or tankless water heater swaps.",
    estimatedMinutes: 3,
    recommendedPlan: "free",
    launchReady: true,
    steps: [
      {
        id: "wh_step_1",
        orderIndex: 0,
        title: "Full water heater",
        instructions: "Capture the whole unit from a few feet back.",
        shotType: "wide",
        overlayType: "full_area",
        aiChecks: ["blur", "wide_shot_detected"],
        required: true,
      },
      {
        id: "wh_step_2",
        orderIndex: 1,
        title: "Model & serial plate",
        instructions: "Straight-on photo of the spec plate so model and serial are readable.",
        shotType: "serial",
        overlayType: "serial_plate",
        aiChecks: ["blur", "unreadable_text", "serial_detected"],
        required: true,
      },
      {
        id: "wh_step_3",
        orderIndex: 2,
        title: "Venting",
        instructions: "Show the vent pipe coming off the top of the unit.",
        shotType: "wide",
        overlayType: "full_area",
        aiChecks: ["blur"],
        required: true,
      },
    ],
    questions: [
      {
        id: "wh_q_1",
        orderIndex: 0,
        prompt: "How old is the current unit (approx)?",
        inputType: "short_text",
        required: false,
      },
    ],
  },
  {
    id: "guide_junk",
    name: "Junk removal quote",
    category: "Junk removal",
    description: "Wide shots of the pile, access path, and any oversized items.",
    isTemplate: true,
    curatedCategory: "service_quote",
    bestFor: "Haulers sizing loads before dispatching a truck.",
    estimatedMinutes: 3,
    recommendedPlan: "free",
    launchReady: true,
    steps: [
      {
        id: "junk_step_1",
        orderIndex: 0,
        title: "Wide shot of the pile",
        instructions: "Stand back so we can see the full size of the load.",
        shotType: "wide",
        overlayType: "full_area",
        aiChecks: ["blur", "wide_shot_detected", "missing_scale"],
        required: true,
      },
      {
        id: "junk_step_2",
        orderIndex: 1,
        title: "Access path",
        instructions: "Show the path our crew will walk from the truck to the pile.",
        shotType: "wide",
        overlayType: "full_area",
        aiChecks: ["blur"],
        required: true,
      },
    ],
    questions: [
      {
        id: "junk_q_1",
        orderIndex: 0,
        prompt: "Any oversized items (mattress, couch, appliance)?",
        inputType: "long_text",
        required: false,
      },
    ],
  },
  {
    id: "guide_landscape",
    name: "Landscaping site survey",
    category: "Landscaping",
    description: "Front yard, back yard, problem areas, and existing irrigation.",
    isTemplate: true,
    curatedCategory: "service_quote",
    bestFor: "Landscapers scoping multi-zone projects remotely.",
    estimatedMinutes: 5,
    recommendedPlan: "pro",
    launchReady: true,
    steps: [
      {
        id: "land_step_1",
        orderIndex: 0,
        title: "Front yard wide shot",
        instructions: "Capture the whole front yard from the street.",
        shotType: "wide",
        overlayType: "full_area",
        aiChecks: ["blur", "wide_shot_detected"],
        required: true,
      },
      {
        id: "land_step_2",
        orderIndex: 1,
        title: "Back yard wide shot",
        instructions: "Capture the whole back yard from one corner.",
        shotType: "wide",
        overlayType: "full_area",
        aiChecks: ["blur", "wide_shot_detected"],
        required: true,
      },
    ],
    questions: [],
  },
  {
    id: "guide_appliance",
    name: "Appliance repair intake",
    category: "Appliance repair",
    description: "Photos of the appliance, model plate, and the fault.",
    isTemplate: true,
    curatedCategory: "service_quote",
    bestFor: "Repair techs diagnosing before the visit.",
    estimatedMinutes: 3,
    recommendedPlan: "free",
    launchReady: true,
    steps: [
      {
        id: "app_step_1",
        orderIndex: 0,
        title: "Full appliance",
        instructions: "Stand back so we can see the whole appliance.",
        shotType: "wide",
        overlayType: "full_area",
        aiChecks: ["blur"],
        required: true,
      },
      {
        id: "app_step_2",
        orderIndex: 1,
        title: "Model plate",
        instructions: "Straight-on shot of the model and serial plate.",
        shotType: "serial",
        overlayType: "serial_plate",
        aiChecks: ["blur", "unreadable_text", "serial_detected"],
        required: true,
      },
    ],
    questions: [],
  },

  // ─── Property, Proof & Records ─────────────────────────────────────────
  {
    id: "guide_move_in_out",
    name: "Move-in / move-out condition",
    category: "Property management",
    description: "Room-by-room condition record with timestamps.",
    isTemplate: true,
    curatedCategory: "property_proof",
    bestFor: "Landlords and property managers documenting unit condition.",
    estimatedMinutes: 8,
    recommendedPlan: "pro",
    launchReady: true,
    steps: [
      {
        id: "mio_step_1",
        orderIndex: 0,
        title: "Living room — wide",
        instructions: "Stand in one corner and capture the whole room.",
        shotType: "wide",
        overlayType: "full_area",
        aiChecks: ["blur", "low_light", "wide_shot_detected"],
        required: true,
      },
      {
        id: "mio_step_2",
        orderIndex: 1,
        title: "Kitchen — wide",
        instructions: "Capture all cabinets and appliances in one frame.",
        shotType: "wide",
        overlayType: "full_area",
        aiChecks: ["blur", "wide_shot_detected"],
        required: true,
      },
      {
        id: "mio_step_3",
        orderIndex: 2,
        title: "Bathroom — wide",
        instructions: "Include the toilet, sink, and tub/shower.",
        shotType: "wide",
        overlayType: "full_area",
        aiChecks: ["blur", "wide_shot_detected"],
        required: true,
      },
      {
        id: "mio_step_4",
        orderIndex: 3,
        title: "Bedroom — wide",
        instructions: "Capture the full bedroom including closet doors.",
        shotType: "wide",
        overlayType: "full_area",
        aiChecks: ["blur", "wide_shot_detected"],
        required: true,
      },
      {
        id: "mio_step_5",
        orderIndex: 4,
        title: "Existing damage close-ups",
        instructions: "Close-up of any scuffs, stains, or damage you spot.",
        shotType: "close_up",
        overlayType: "close_up",
        aiChecks: ["blur", "damage_visible", "close_up_detected"],
        required: false,
      },
    ],
    questions: [
      {
        id: "mio_q_1",
        orderIndex: 0,
        prompt: "Is this a move-in or move-out walkthrough?",
        inputType: "single_select",
        options: ["Move-in", "Move-out"],
        required: true,
      },
    ],
  },
  {
    id: "guide_proof_of_completion",
    name: "Proof of completion",
    category: "Field service",
    description: "Before / after shots that double as the customer receipt.",
    isTemplate: true,
    curatedCategory: "property_proof",
    bestFor: "Field crews documenting finished work for invoicing.",
    estimatedMinutes: 2,
    recommendedPlan: "free",
    launchReady: true,
    steps: [
      {
        id: "poc_step_1",
        orderIndex: 0,
        title: "Before shot",
        instructions: "Wide shot of the area before work started.",
        shotType: "wide",
        overlayType: "before_after",
        aiChecks: ["blur", "wide_shot_detected"],
        required: true,
      },
      {
        id: "poc_step_2",
        orderIndex: 1,
        title: "After shot — same angle",
        instructions: "Same angle and framing as the before photo.",
        shotType: "wide",
        overlayType: "before_after",
        aiChecks: ["blur", "wide_shot_detected"],
        required: true,
      },
      {
        id: "poc_step_3",
        orderIndex: 2,
        title: "Receipt / invoice (optional)",
        instructions: "Photo of the receipt or invoice if applicable.",
        shotType: "document",
        overlayType: "label",
        aiChecks: ["blur", "unreadable_text", "receipt_detected"],
        required: false,
      },
    ],
    questions: [],
  },
  {
    id: "guide_insurance_claim",
    name: "Insurance claim photo packet",
    category: "Insurance",
    description: "Damage overview, close-ups, and supporting documents.",
    isTemplate: true,
    curatedCategory: "property_proof",
    bestFor: "Adjusters collecting structured loss documentation.",
    estimatedMinutes: 6,
    recommendedPlan: "team",
    launchReady: true,
    steps: [
      {
        id: "ic_step_1",
        orderIndex: 0,
        title: "Wide shot of the damaged area",
        instructions: "Capture the whole damaged area in context.",
        shotType: "wide",
        overlayType: "full_area",
        aiChecks: ["blur", "wide_shot_detected"],
        required: true,
      },
      {
        id: "ic_step_2",
        orderIndex: 1,
        title: "Close-up of the damage",
        instructions: "Get close enough to see the extent of the damage.",
        shotType: "close_up",
        overlayType: "close_up",
        aiChecks: ["blur", "damage_visible", "close_up_detected"],
        required: true,
      },
      {
        id: "ic_step_3",
        orderIndex: 2,
        title: "Reference object for scale",
        instructions: "Place a coin, ruler, or hand near the damage for scale.",
        shotType: "close_up",
        overlayType: "scale_required",
        aiChecks: ["missing_scale", "close_up_detected"],
        required: true,
      },
      {
        id: "ic_step_4",
        orderIndex: 3,
        title: "Receipt / proof of ownership",
        instructions: "Photo of any receipt, invoice, or registration.",
        shotType: "document",
        overlayType: "label",
        aiChecks: ["blur", "unreadable_text", "receipt_detected"],
        required: false,
      },
    ],
    questions: [
      {
        id: "ic_q_1",
        orderIndex: 0,
        prompt: "Date the damage occurred",
        inputType: "short_text",
        required: true,
      },
      {
        id: "ic_q_2",
        orderIndex: 1,
        prompt: "Brief description of what happened",
        inputType: "long_text",
        required: true,
      },
    ],
  },

  // ─── Product Support & Claims ──────────────────────────────────────────
  {
    id: "guide_warranty_claim",
    name: "Warranty claim intake",
    category: "Product support",
    description: "Product, serial, and the issue — everything support needs.",
    isTemplate: true,
    curatedCategory: "product_support",
    bestFor: "Brands processing warranty claims without a phone call.",
    estimatedMinutes: 4,
    recommendedPlan: "pro",
    launchReady: true,
    steps: [
      {
        id: "wc_step_1",
        orderIndex: 0,
        title: "Whole product",
        instructions: "Photo of the whole product on a clean surface.",
        shotType: "wide",
        overlayType: "full_area",
        aiChecks: ["blur", "wide_shot_detected"],
        required: true,
      },
      {
        id: "wc_step_2",
        orderIndex: 1,
        title: "Serial number",
        instructions: "Close-up of the serial number / model label.",
        shotType: "serial",
        overlayType: "serial_plate",
        aiChecks: ["blur", "unreadable_text", "serial_detected"],
        required: true,
      },
      {
        id: "wc_step_3",
        orderIndex: 2,
        title: "The issue",
        instructions: "Close-up showing the defect or damage.",
        shotType: "close_up",
        overlayType: "close_up",
        aiChecks: ["blur", "damage_visible", "close_up_detected"],
        required: true,
      },
      {
        id: "wc_step_4",
        orderIndex: 3,
        title: "Receipt or proof of purchase",
        instructions: "Photo of the receipt or order confirmation.",
        shotType: "document",
        overlayType: "label",
        aiChecks: ["blur", "unreadable_text", "receipt_detected"],
        required: true,
      },
    ],
    questions: [
      {
        id: "wc_q_1",
        orderIndex: 0,
        prompt: "What's wrong with the product?",
        inputType: "long_text",
        required: true,
      },
    ],
  },
  {
    id: "guide_return_intake",
    name: "Return / RMA intake",
    category: "E-commerce",
    description: "Confirm what shipped, the condition, and packaging.",
    isTemplate: true,
    curatedCategory: "product_support",
    bestFor: "E-commerce ops triaging returns before approving an RMA.",
    estimatedMinutes: 3,
    recommendedPlan: "free",
    launchReady: true,
    steps: [
      {
        id: "ret_step_1",
        orderIndex: 0,
        title: "Item as received",
        instructions: "Photo of the item still in the original packaging.",
        shotType: "wide",
        overlayType: "full_area",
        aiChecks: ["blur"],
        required: true,
      },
      {
        id: "ret_step_2",
        orderIndex: 1,
        title: "Issue close-up",
        instructions: "Close-up of the defect or wrong item.",
        shotType: "close_up",
        overlayType: "close_up",
        aiChecks: ["blur", "damage_visible", "close_up_detected"],
        required: true,
      },
      {
        id: "ret_step_3",
        orderIndex: 2,
        title: "Packing slip",
        instructions: "Photo of the packing slip or order number.",
        shotType: "document",
        overlayType: "label",
        aiChecks: ["unreadable_text", "receipt_detected"],
        required: true,
      },
    ],
    questions: [
      {
        id: "ret_q_1",
        orderIndex: 0,
        prompt: "Reason for the return",
        inputType: "single_select",
        options: ["Defective", "Wrong item", "Doesn't fit", "Changed my mind", "Other"],
        required: true,
      },
    ],
  },
  {
    id: "guide_pest",
    name: "Pest / wildlife report",
    category: "Pest control",
    description: "Photos and short context for safe identification.",
    isTemplate: true,
    curatedCategory: "product_support",
    bestFor: "Pest control teams identifying species before dispatch.",
    estimatedMinutes: 3,
    recommendedPlan: "free",
    launchReady: true,
    steps: [
      {
        id: "pest_step_1",
        orderIndex: 0,
        title: "Where you saw it",
        instructions: "Wide shot of the area where you noticed activity.",
        shotType: "wide",
        overlayType: "full_area",
        aiChecks: ["blur"],
        required: true,
      },
      {
        id: "pest_step_2",
        orderIndex: 1,
        title: "Close-up (from a safe distance)",
        instructions: "Zoom in if you can do so safely. Don't get close to the animal.",
        shotType: "close_up",
        overlayType: "close_up",
        aiChecks: ["blur", "unsafe_condition"],
        required: false,
      },
    ],
    questions: [
      {
        id: "pest_q_1",
        orderIndex: 0,
        prompt: "When did you last see activity?",
        inputType: "short_text",
        required: true,
      },
    ],
  },

  // ─── Sales, Listings & Marketing ───────────────────────────────────────
  {
    id: "guide_real_estate_listing",
    name: "Real estate listing shoot",
    category: "Real estate",
    description: "Listing-quality photos of every key room and exterior.",
    isTemplate: true,
    curatedCategory: "sales_listing",
    bestFor: "Agents preparing a new listing without a pro photographer.",
    estimatedMinutes: 10,
    recommendedPlan: "pro",
    launchReady: true,
    steps: [
      {
        id: "re_step_1",
        orderIndex: 0,
        title: "Front exterior",
        instructions: "Stand across the street and capture the whole front of the home.",
        shotType: "wide",
        overlayType: "full_area",
        aiChecks: ["blur", "wide_shot_detected"],
        required: true,
      },
      {
        id: "re_step_2",
        orderIndex: 1,
        title: "Living room",
        instructions: "Stand in one corner so all furniture is in frame.",
        shotType: "wide",
        overlayType: "full_area",
        aiChecks: ["blur", "low_light", "wide_shot_detected"],
        required: true,
      },
      {
        id: "re_step_3",
        orderIndex: 2,
        title: "Kitchen",
        instructions: "Capture cabinets, counters, and appliances together.",
        shotType: "wide",
        overlayType: "full_area",
        aiChecks: ["blur", "low_light", "wide_shot_detected"],
        required: true,
      },
      {
        id: "re_step_4",
        orderIndex: 3,
        title: "Primary bedroom",
        instructions: "Capture the bed and as much of the room as possible.",
        shotType: "wide",
        overlayType: "full_area",
        aiChecks: ["blur", "wide_shot_detected"],
        required: true,
      },
      {
        id: "re_step_5",
        orderIndex: 4,
        title: "Backyard",
        instructions: "Stand at the back door and capture the whole yard.",
        shotType: "wide",
        overlayType: "full_area",
        aiChecks: ["blur", "wide_shot_detected"],
        required: true,
      },
    ],
    questions: [
      {
        id: "re_q_1",
        orderIndex: 0,
        prompt: "Anything you want highlighted in the listing?",
        inputType: "long_text",
        required: false,
      },
    ],
  },
  {
    id: "guide_marketplace_resale",
    name: "Marketplace resale shoot",
    category: "Resale",
    description: "Studio-style photos for Facebook Marketplace, eBay, etc.",
    isTemplate: true,
    curatedCategory: "sales_listing",
    bestFor: "Resellers listing items quickly with consistent photos.",
    estimatedMinutes: 4,
    recommendedPlan: "free",
    launchReady: true,
    steps: [
      {
        id: "mr_step_1",
        orderIndex: 0,
        title: "Hero shot — whole item",
        instructions: "Place on a clean background and capture the whole item.",
        shotType: "wide",
        overlayType: "full_area",
        aiChecks: ["blur", "wide_shot_detected"],
        required: true,
      },
      {
        id: "mr_step_2",
        orderIndex: 1,
        title: "Brand or model label",
        instructions: "Close-up of the label or logo.",
        shotType: "label",
        overlayType: "label",
        aiChecks: ["blur", "unreadable_text", "label_detected"],
        required: true,
      },
      {
        id: "mr_step_3",
        orderIndex: 2,
        title: "Any flaws (be honest!)",
        instructions: "Close-up of any wear, scratches, or imperfections.",
        shotType: "close_up",
        overlayType: "close_up",
        aiChecks: ["blur", "damage_visible", "close_up_detected"],
        required: false,
      },
    ],
    questions: [
      {
        id: "mr_q_1",
        orderIndex: 0,
        prompt: "Asking price",
        inputType: "number",
        required: false,
      },
    ],
  },
  {
    id: "guide_vehicle_listing",
    name: "Used vehicle listing",
    category: "Automotive",
    description: "Exterior, interior, dash, and VIN — everything a buyer asks for.",
    isTemplate: true,
    curatedCategory: "sales_listing",
    bestFor: "Dealers and private sellers listing used vehicles.",
    estimatedMinutes: 6,
    recommendedPlan: "pro",
    launchReady: true,
    steps: [
      {
        id: "veh_step_1",
        orderIndex: 0,
        title: "3/4 front exterior",
        instructions: "Stand at the front-left corner and capture the whole car.",
        shotType: "wide",
        overlayType: "full_area",
        aiChecks: ["blur", "wide_shot_detected"],
        required: true,
      },
      {
        id: "veh_step_2",
        orderIndex: 1,
        title: "3/4 rear exterior",
        instructions: "Stand at the rear-right corner and capture the whole car.",
        shotType: "wide",
        overlayType: "full_area",
        aiChecks: ["blur", "wide_shot_detected"],
        required: true,
      },
      {
        id: "veh_step_3",
        orderIndex: 2,
        title: "Dashboard with mileage",
        instructions: "Photo of the dash showing odometer reading.",
        shotType: "close_up",
        overlayType: "close_up",
        aiChecks: ["blur", "unreadable_text", "close_up_detected"],
        required: true,
      },
      {
        id: "veh_step_4",
        orderIndex: 3,
        title: "Interior — front seats",
        instructions: "Open the door and capture the front seats and dash.",
        shotType: "wide",
        overlayType: "full_area",
        aiChecks: ["blur", "low_light"],
        required: true,
      },
      {
        id: "veh_step_5",
        orderIndex: 4,
        title: "VIN plate",
        instructions: "Close-up of the VIN at the base of the windshield.",
        shotType: "serial",
        overlayType: "serial_plate",
        aiChecks: ["blur", "unreadable_text", "serial_detected"],
        required: true,
      },
    ],
    questions: [
      {
        id: "veh_q_1",
        orderIndex: 0,
        prompt: "Any known issues we should mention?",
        inputType: "long_text",
        required: false,
      },
    ],
  },

  // ─── Custom Business Intake ────────────────────────────────────────────
  {
    id: "guide_blank_intake",
    name: "Blank intake (you customize)",
    category: "Custom",
    description: "A near-empty starting point — name it, add steps, send.",
    isTemplate: true,
    curatedCategory: "custom_intake",
    bestFor: "Anyone who wants to start from scratch and shape their own flow.",
    estimatedMinutes: 2,
    recommendedPlan: "free",
    launchReady: true,
    steps: [
      {
        id: "blank_step_1",
        orderIndex: 0,
        title: "Wide shot",
        instructions: "Stand back and capture the whole subject.",
        shotType: "wide",
        overlayType: "full_area",
        aiChecks: ["blur", "wide_shot_detected"],
        required: true,
      },
      {
        id: "blank_step_2",
        orderIndex: 1,
        title: "Close-up",
        instructions: "Get close on the most important detail.",
        shotType: "close_up",
        overlayType: "close_up",
        aiChecks: ["blur", "close_up_detected"],
        required: false,
      },
    ],
    questions: [
      {
        id: "blank_q_1",
        orderIndex: 0,
        prompt: "Any extra context for our team?",
        inputType: "long_text",
        required: false,
      },
    ],
  },
  {
    id: "guide_universal_intake",
    name: "Universal 5-shot intake",
    category: "Custom",
    description: "Wide, close-up, label, scale reference, and a free-form context shot.",
    isTemplate: true,
    curatedCategory: "custom_intake",
    bestFor: "Solo operators who want one good guide for everything.",
    estimatedMinutes: 5,
    recommendedPlan: "free",
    launchReady: true,
    steps: [
      {
        id: "uni_step_1",
        orderIndex: 0,
        title: "Wide shot",
        instructions: "Capture the full subject in context.",
        shotType: "wide",
        overlayType: "full_area",
        aiChecks: ["blur", "wide_shot_detected"],
        required: true,
      },
      {
        id: "uni_step_2",
        orderIndex: 1,
        title: "Close-up",
        instructions: "Zoom in on the most important detail.",
        shotType: "close_up",
        overlayType: "close_up",
        aiChecks: ["blur", "close_up_detected"],
        required: true,
      },
      {
        id: "uni_step_3",
        orderIndex: 2,
        title: "Any label or model number",
        instructions: "Straight-on shot of any label or stamp.",
        shotType: "label",
        overlayType: "label",
        aiChecks: ["blur", "unreadable_text", "label_detected"],
        required: false,
      },
      {
        id: "uni_step_4",
        orderIndex: 3,
        title: "Scale reference",
        instructions: "Place a hand, coin, or ruler in the shot for scale.",
        shotType: "close_up",
        overlayType: "scale_required",
        aiChecks: ["missing_scale", "close_up_detected"],
        required: false,
      },
      {
        id: "uni_step_5",
        orderIndex: 4,
        title: "Anything else worth showing?",
        instructions: "One extra shot — your call.",
        shotType: "wide",
        overlayType: "full_area",
        aiChecks: ["blur"],
        required: false,
      },
    ],
    questions: [
      {
        id: "uni_q_1",
        orderIndex: 0,
        prompt: "What is this for?",
        inputType: "short_text",
        required: false,
      },
    ],
  },

  // ─── Internal-only templates (admin toggle) ────────────────────────────
  // These mirror raw rows from the Template Directory workbook and stay
  // hidden from the public library until curated.
  {
    id: "guide_internal_seed_solar_audit",
    name: "[Internal] Solar panel audit",
    category: "Energy",
    description: "Raw template imported from the directory — needs review before launch.",
    isTemplate: true,
    launchReady: false,
    steps: [
      {
        id: "sol_step_1",
        orderIndex: 0,
        title: "Roof wide shot",
        instructions: "Wide shot of the roof from the ground.",
        shotType: "wide",
        overlayType: "full_area",
        aiChecks: ["blur", "wide_shot_detected"],
        required: true,
      },
      {
        id: "sol_step_2",
        orderIndex: 1,
        title: "Inverter label",
        instructions: "Close-up of the inverter spec label.",
        shotType: "serial",
        overlayType: "serial_plate",
        aiChecks: ["blur", "unreadable_text", "serial_detected"],
        required: true,
      },
    ],
    questions: [],
  },
  {
    id: "guide_internal_seed_pool_inspection",
    name: "[Internal] Pool inspection",
    category: "Pool & spa",
    description: "Raw template imported from the directory — needs review before launch.",
    isTemplate: true,
    launchReady: false,
    steps: [
      {
        id: "pool_step_1",
        orderIndex: 0,
        title: "Pool wide shot",
        instructions: "Stand at the deep end and capture the whole pool.",
        shotType: "wide",
        overlayType: "full_area",
        aiChecks: ["blur", "wide_shot_detected"],
        required: true,
      },
      {
        id: "pool_step_2",
        orderIndex: 1,
        title: "Pump and filter",
        instructions: "Wide shot of the pump and filter equipment.",
        shotType: "wide",
        overlayType: "full_area",
        aiChecks: ["blur"],
        required: true,
      },
    ],
    questions: [],
  },
];
