// Seed guide templates. Adding a new guide = adding an entry here.
// Pages MUST NOT hardcode guides — they read from this config.
import type { PhotoGuide } from "@/types/photobrief";

export const guideTemplates: PhotoGuide[] = [
  {
    id: "guide_leak",
    name: "Leak diagnosis intake",
    category: "Plumbing",
    description: "Capture the leak, surrounding area, and shut-off valve so we can quote accurately.",
    isTemplate: true,
    steps: [
      {
        id: "leak_step_1",
        orderIndex: 0,
        title: "Wide shot of the area",
        instructions: "Stand back and capture the whole space around the leak.",
        shotType: "wide",
        overlayType: "full_area",
        aiChecks: ["blur", "low_light", "wide_shot_detected"],
        required: true,
      },
      {
        id: "leak_step_2",
        orderIndex: 1,
        title: "Close-up of the leak",
        instructions: "Get close enough to see exactly where water is coming from.",
        shotType: "close_up",
        overlayType: "close_up",
        aiChecks: ["blur", "damage_visible", "close_up_detected"],
        required: true,
      },
      {
        id: "leak_step_3",
        orderIndex: 2,
        title: "Shut-off valve",
        instructions: "Photo of the nearest shut-off valve so we know what's accessible.",
        shotType: "wide",
        overlayType: "full_area",
        aiChecks: ["blur", "missing_required_item"],
        required: true,
      },
      {
        id: "leak_step_4",
        orderIndex: 3,
        title: "Supply line label",
        instructions: "Straight-on photo of any label or stamp on the supply line.",
        shotType: "label",
        overlayType: "label",
        aiChecks: ["blur", "unreadable_text", "label_detected"],
        required: false,
      },
    ],
    questions: [
      {
        id: "leak_q_1",
        orderIndex: 0,
        prompt: "When did you first notice the leak?",
        inputType: "short_text",
        required: true,
      },
      {
        id: "leak_q_2",
        orderIndex: 1,
        prompt: "Is water actively running right now?",
        inputType: "single_select",
        options: ["Yes", "No", "Slow drip"],
        required: true,
      },
    ],
  },
  {
    id: "guide_water_heater",
    name: "Water heater replacement",
    category: "Plumbing",
    description: "Photos of the unit, model plate, venting, and surrounding clearance.",
    isTemplate: true,
    steps: [
      {
        id: "wh_step_1",
        orderIndex: 0,
        title: "Full water heater",
        instructions: "Capture the whole unit from a few feet back.",
        shotType: "wide",
        overlayType: "full_area",
        aiChecks: ["blur", "wide_shot_detected"],
        required: true,
      },
      {
        id: "wh_step_2",
        orderIndex: 1,
        title: "Model & serial plate",
        instructions: "Straight-on photo of the spec plate so model and serial are readable.",
        shotType: "serial",
        overlayType: "serial_plate",
        aiChecks: ["blur", "unreadable_text", "serial_detected"],
        required: true,
      },
      {
        id: "wh_step_3",
        orderIndex: 2,
        title: "Venting",
        instructions: "Show the vent pipe coming off the top of the unit.",
        shotType: "wide",
        overlayType: "full_area",
        aiChecks: ["blur"],
        required: true,
      },
    ],
    questions: [
      {
        id: "wh_q_1",
        orderIndex: 0,
        prompt: "How old is the current unit (approx)?",
        inputType: "short_text",
        required: false,
      },
    ],
  },
  {
    id: "guide_junk",
    name: "Junk removal quote",
    category: "Junk removal",
    description: "Wide shots of the pile, access path, and any oversized items.",
    isTemplate: true,
    steps: [
      {
        id: "junk_step_1",
        orderIndex: 0,
        title: "Wide shot of the pile",
        instructions: "Stand back so we can see the full size of the load.",
        shotType: "wide",
        overlayType: "full_area",
        aiChecks: ["blur", "wide_shot_detected", "missing_scale"],
        required: true,
      },
      {
        id: "junk_step_2",
        orderIndex: 1,
        title: "Access path",
        instructions: "Show the path our crew will walk from the truck to the pile.",
        shotType: "wide",
        overlayType: "full_area",
        aiChecks: ["blur"],
        required: true,
      },
    ],
    questions: [
      {
        id: "junk_q_1",
        orderIndex: 0,
        prompt: "Any oversized items (mattress, couch, appliance)?",
        inputType: "long_text",
        required: false,
      },
    ],
  },
  {
    id: "guide_landscape",
    name: "Landscaping site survey",
    category: "Landscaping",
    description: "Front yard, back yard, problem areas, and existing irrigation.",
    isTemplate: true,
    steps: [
      {
        id: "land_step_1",
        orderIndex: 0,
        title: "Front yard wide shot",
        instructions: "Capture the whole front yard from the street.",
        shotType: "wide",
        overlayType: "full_area",
        aiChecks: ["blur", "wide_shot_detected"],
        required: true,
      },
      {
        id: "land_step_2",
        orderIndex: 1,
        title: "Back yard wide shot",
        instructions: "Capture the whole back yard from one corner.",
        shotType: "wide",
        overlayType: "full_area",
        aiChecks: ["blur", "wide_shot_detected"],
        required: true,
      },
    ],
    questions: [],
  },
  {
    id: "guide_appliance",
    name: "Appliance repair intake",
    category: "Appliance repair",
    description: "Photos of the appliance, model plate, and the fault.",
    isTemplate: true,
    steps: [
      {
        id: "app_step_1",
        orderIndex: 0,
        title: "Full appliance",
        instructions: "Stand back so we can see the whole appliance.",
        shotType: "wide",
        overlayType: "full_area",
        aiChecks: ["blur"],
        required: true,
      },
      {
        id: "app_step_2",
        orderIndex: 1,
        title: "Model plate",
        instructions: "Straight-on shot of the model and serial plate.",
        shotType: "serial",
        overlayType: "serial_plate",
        aiChecks: ["blur", "unreadable_text", "serial_detected"],
        required: true,
      },
    ],
    questions: [],
  },
  {
    id: "guide_pest",
    name: "Pest / wildlife report",
    category: "Pest control",
    description: "Photos and short context for safe identification.",
    isTemplate: true,
    steps: [
      {
        id: "pest_step_1",
        orderIndex: 0,
        title: "Where you saw it",
        instructions: "Wide shot of the area where you noticed activity.",
        shotType: "wide",
        overlayType: "full_area",
        aiChecks: ["blur"],
        required: true,
      },
      {
        id: "pest_step_2",
        orderIndex: 1,
        title: "Close-up (from a safe distance)",
        instructions: "Zoom in if you can do so safely. Don't get close to the animal.",
        shotType: "close_up",
        overlayType: "close_up",
        aiChecks: ["blur", "unsafe_condition"],
        required: false,
      },
    ],
    questions: [
      {
        id: "pest_q_1",
        orderIndex: 0,
        prompt: "When did you last see activity?",
        inputType: "short_text",
        required: true,
      },
    ],
  },
];
