// Mock fixtures still used by submission/request UIs until later stages
// replace them with live queries. The workspace + team-member mocks were
// removed in Stage 1 (live data via useCurrentWorkspace + useTeamMembers).
import type { PhotoBriefRequest, Submission } from "@/types/photobrief";
import { guideTemplates } from "@/config/guideTemplates";

const guideById = (id: string) => guideTemplates.find((g) => g.id === id);

const hoursAgo = (h: number) => new Date(Date.now() - 1000 * 60 * 60 * h).toISOString();
const minutesAgo = (m: number) => new Date(Date.now() - 1000 * 60 * m).toISOString();

export const mockRequests: PhotoBriefRequest[] = [
  {
    id: "req_1",
    workspaceId: "ws_demo",
    guideId: "guide_leak",
    guideName: guideById("guide_leak")?.name ?? "",
    recipientName: "Maria Alvarez",
    recipientContact: "maria@example.com",
    token: "abc123",
    status: "in_progress",
    createdAt: hoursAgo(3),
    readinessScore: 64,
    missingItems: ["Shut-off valve close-up", "Supply line label"],
    lastActivityAt: minutesAgo(18),
    assigneeId: "u_pat",
    assigneeName: "Patrick Owens",
  },
  {
    id: "req_2",
    workspaceId: "ws_demo",
    guideId: "guide_water_heater",
    guideName: guideById("guide_water_heater")?.name ?? "",
    recipientName: "Devon Park",
    recipientContact: "555-0142",
    token: "def456",
    status: "sent",
    createdAt: hoursAgo(26),
    missingItems: ["Hasn't opened link"],
    lastActivityAt: hoursAgo(26),
    assigneeId: "u_jen",
    assigneeName: "Jen Hughes",
  },
  {
    id: "req_3",
    workspaceId: "ws_demo",
    guideId: "guide_junk",
    guideName: guideById("guide_junk")?.name ?? "",
    recipientName: "Priya Shah",
    recipientContact: "priya@example.com",
    token: "ghi789",
    status: "submitted",
    createdAt: hoursAgo(48),
    readinessScore: 92,
    missingItems: [],
    lastActivityAt: minutesAgo(30),
    assigneeId: "u_pat",
    assigneeName: "Patrick Owens",
  },
  {
    id: "req_4",
    workspaceId: "ws_demo",
    guideId: "guide_landscape",
    guideName: guideById("guide_landscape")?.name ?? "",
    recipientName: "Jordan Lee",
    recipientContact: "jordan@example.com",
    token: "jkl012",
    status: "needs_customer_action",
    createdAt: hoursAgo(72),
    readinessScore: 41,
    missingItems: ["Property line wide shot", "Slope reference"],
    lastActivityAt: hoursAgo(20),
    assigneeId: "u_marco",
    assigneeName: "Marco Diaz",
  },
  {
    id: "req_5",
    workspaceId: "ws_demo",
    guideId: "guide_water_heater",
    guideName: guideById("guide_water_heater")?.name ?? "",
    recipientName: "Casey Wong",
    recipientContact: "casey@example.com",
    token: "mno345",
    status: "reviewed",
    createdAt: hoursAgo(120),
    readinessScore: 100,
    missingItems: [],
    lastActivityAt: hoursAgo(30),
    assigneeId: "u_jen",
    assigneeName: "Jen Hughes",
  },
  {
    id: "req_6",
    workspaceId: "ws_demo",
    guideId: "guide_junk",
    guideName: guideById("guide_junk")?.name ?? "",
    recipientName: "Theo Nakamura",
    recipientContact: "theo@example.com",
    token: "pqr678",
    status: "submitted",
    createdAt: hoursAgo(8),
    readinessScore: 88,
    missingItems: [],
    lastActivityAt: minutesAgo(120),
    assigneeId: "u_marco",
    assigneeName: "Marco Diaz",
  },
];

export const mockSubmissions: Submission[] = [
  {
    id: "sub_1",
    requestId: "req_3",
    recipientName: "Priya Shah",
    recipientContact: "priya@example.com",
    guideName: guideById("guide_junk")?.name ?? "",
    requestType: "Junk removal quote",
    status: "new",
    readinessScore: 92,
    aiSummary:
      "Driveway pile of mixed household junk, roughly one truckload. Includes a queen mattress, small couch, two end tables, and ~6 bags of household waste. Driveway access is clear and flat — no stairs.",
    suggestedNextAction: "Send a same-day quote for a half-truck haul (~$320).",
    submittedAt: minutesAgo(30),
    assigneeId: "u_pat",
    assigneeName: "Patrick Owens",
    missingItems: [],
    extractedDetails: [
      { label: "Estimated volume", value: "~½ truck (8 cu yd)", confidence: 0.82 },
      { label: "Heavy items", value: "Queen mattress, small couch", confidence: 0.91 },
      { label: "Access", value: "Driveway, flat, no stairs", confidence: 0.95 },
      { label: "Hazardous materials", value: "None detected", confidence: 0.88 },
    ],
    shots: [
      {
        id: "shot_1_1",
        stepId: "junk_step_1",
        orderIndex: 0,
        title: "Wide shot of the pile",
        instructions: "Stand back so the whole pile is in frame.",
        shotType: "wide",
        imageUrl: "https://images.unsplash.com/photo-1530587191325-3db32d826c18?w=800&q=80",
        capturedAt: minutesAgo(45),
        feedback: {
          severity: "pass",
          headline: "Sharp, well-framed wide shot",
          detail: "Whole pile is visible with good lighting and no motion blur.",
          checks: [
            { type: "wide_shot_detected", severity: "pass", label: "Wide shot detected" },
            { type: "blur", severity: "pass", label: "In focus" },
            { type: "low_light", severity: "pass", label: "Good lighting" },
          ],
        },
      },
      {
        id: "shot_1_2",
        stepId: "junk_step_2",
        orderIndex: 1,
        title: "Close-up of heavy items",
        instructions: "Get close on anything heavy or oversized (mattress, appliances).",
        shotType: "close_up",
        imageUrl: "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=800&q=80",
        capturedAt: minutesAgo(43),
        feedback: {
          severity: "pass",
          headline: "Mattress and couch clearly visible",
          checks: [
            { type: "close_up_detected", severity: "pass", label: "Close-up detected" },
            { type: "blur", severity: "pass", label: "In focus" },
          ],
        },
      },
      {
        id: "shot_1_3",
        stepId: "junk_step_3",
        orderIndex: 2,
        title: "Access path",
        instructions: "Show the route from the curb to the pile.",
        shotType: "wide",
        imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
        capturedAt: minutesAgo(40),
        feedback: {
          severity: "pass",
          headline: "Clear, flat access — no obstacles",
        },
      },
    ],
    customerAnswers: [
      { prompt: "When would you like this picked up?", answer: "Today or tomorrow if possible." },
      { prompt: "Is anyone home during business hours?", answer: "Yes, after 2pm." },
      { prompt: "Any fragile or hazardous items?", answer: "No." },
    ],
    internalNotes: [
      {
        id: "note_1_1",
        authorName: "Patrick Owens",
        authorInitials: "PO",
        body: "Same neighborhood as the Henderson job — can bundle on the way back.",
        createdAt: minutesAgo(12),
      },
    ],
    activity: [
      { id: "ev_1_1", type: "request_sent", label: "Request sent to Priya", actor: "Patrick", at: hoursAgo(2) },
      { id: "ev_1_2", type: "recipient_opened", label: "Priya opened the link", actor: "Priya Shah", at: hoursAgo(1) },
      { id: "ev_1_3", type: "shot_uploaded", label: "Uploaded wide shot", actor: "Priya Shah", at: minutesAgo(45) },
      { id: "ev_1_4", type: "shot_uploaded", label: "Uploaded close-up", actor: "Priya Shah", at: minutesAgo(43) },
      { id: "ev_1_5", type: "shot_uploaded", label: "Uploaded access path", actor: "Priya Shah", at: minutesAgo(40) },
      { id: "ev_1_6", type: "answers_submitted", label: "Answered context questions", actor: "Priya Shah", at: minutesAgo(35) },
      { id: "ev_1_7", type: "submission_received", label: "Submission received", actor: "Priya Shah", at: minutesAgo(30) },
      { id: "ev_1_8", type: "ai_review_completed", label: "AI review completed (readiness 92)", actor: "PhotoBrief AI", at: minutesAgo(29) },
    ],
  },
  {
    id: "sub_2",
    requestId: "req_old",
    recipientName: "Sam Rivera",
    recipientContact: "sam@example.com",
    guideName: guideById("guide_leak")?.name ?? "",
    requestType: "Leak diagnosis",
    status: "needs_more",
    readinessScore: 58,
    aiSummary:
      "Under-sink leak is clearly visible at the supply-line connection. Shut-off valve photo is missing and the supply-line label is too blurry to read. Need 2 more shots before we can quote.",
    suggestedNextAction: "Request a sharper supply-line label and the shut-off valve photo.",
    submittedAt: hoursAgo(5),
    assigneeId: "u_jen",
    assigneeName: "Jen Hughes",
    missingItems: ["Shut-off valve close-up", "Readable supply-line label"],
    extractedDetails: [
      { label: "Leak location", value: "Under kitchen sink, hot supply line", confidence: 0.86 },
      { label: "Active flow", value: "Slow drip", confidence: 0.78 },
      { label: "Visible damage", value: "Cabinet base water-stained", confidence: 0.7 },
    ],
    shots: [
      {
        id: "shot_2_1",
        stepId: "leak_step_1",
        orderIndex: 0,
        title: "Wide shot of the area",
        shotType: "wide",
        imageUrl: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80",
        capturedAt: hoursAgo(6),
        feedback: { severity: "pass", headline: "Clear view of the cabinet area" },
      },
      {
        id: "shot_2_2",
        stepId: "leak_step_2",
        orderIndex: 1,
        title: "Close-up of the leak",
        shotType: "close_up",
        imageUrl: "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=800&q=80",
        capturedAt: hoursAgo(6),
        feedback: {
          severity: "pass",
          headline: "Leak source clearly visible",
          detail: "Drip is at the supply-line nut.",
        },
      },
      {
        id: "shot_2_3",
        stepId: "leak_step_3",
        orderIndex: 2,
        title: "Shut-off valve",
        shotType: "wide",
        missing: true,
        feedback: {
          severity: "fail",
          headline: "Missing — never captured",
          detail: "We need to know what the shut-off looks like before sending a tech.",
        },
      },
      {
        id: "shot_2_4",
        stepId: "leak_step_4",
        orderIndex: 3,
        title: "Supply line label",
        shotType: "label",
        imageUrl: "https://images.unsplash.com/photo-1611078489935-0cb964de46d6?w=800&q=80",
        capturedAt: hoursAgo(5),
        feedback: {
          severity: "warn",
          headline: "Label text is unreadable",
          detail: "Photo is too far away. Ask for a straight-on close-up.",
          checks: [
            { type: "unreadable_text", severity: "fail", label: "Text not readable" },
            { type: "blur", severity: "warn", label: "Slight motion blur" },
          ],
        },
      },
    ],
    customerAnswers: [
      { prompt: "When did you first notice the leak?", answer: "About 3 days ago." },
      { prompt: "Is water actively running right now?", answer: "Slow drip" },
    ],
    internalNotes: [
      {
        id: "note_2_1",
        authorName: "Jen Hughes",
        authorInitials: "JH",
        body: "Likely a 1/2\" compression nut. Hold quote until we see the label.",
        createdAt: hoursAgo(4),
      },
    ],
    activity: [
      { id: "ev_2_1", type: "request_sent", label: "Request sent to Sam", actor: "Jen", at: hoursAgo(8) },
      { id: "ev_2_2", type: "submission_received", label: "Submission received", actor: "Sam Rivera", at: hoursAgo(5) },
      { id: "ev_2_3", type: "ai_review_completed", label: "AI flagged 2 missing items", actor: "PhotoBrief AI", at: hoursAgo(5) },
      { id: "ev_2_4", type: "reviewer_note", label: "Jen added an internal note", actor: "Jen Hughes", at: hoursAgo(4) },
    ],
  },
  {
    id: "sub_3",
    requestId: "req_old2",
    recipientName: "Casey Wong",
    recipientContact: "casey@example.com",
    guideName: guideById("guide_water_heater")?.name ?? "",
    requestType: "Water heater replacement",
    status: "reviewed",
    readinessScore: 100,
    aiSummary:
      "50-gallon gas water heater, AO Smith GCV-50, installed 2014. Adequate clearance on all sides, vent in good condition, no signs of leaks.",
    suggestedNextAction: "Quote standard 50-gallon gas replacement.",
    submittedAt: hoursAgo(30),
    assigneeId: "u_pat",
    assigneeName: "Patrick Owens",
    missingItems: [],
    extractedDetails: [
      { label: "Make / Model", value: "AO Smith GCV-50", confidence: 0.97 },
      { label: "Capacity", value: "50 gal", confidence: 0.99 },
      { label: "Fuel", value: "Natural gas", confidence: 0.95 },
      { label: "Install year", value: "2014", confidence: 0.9 },
      { label: "Clearance", value: "Adequate (>6\" all sides)", confidence: 0.84 },
    ],
    shots: [
      {
        id: "shot_3_1",
        orderIndex: 0,
        title: "Wide shot of the unit",
        shotType: "wide",
        imageUrl: "https://images.unsplash.com/photo-1581094288338-2314dddb7ece?w=800&q=80",
        capturedAt: hoursAgo(31),
        feedback: { severity: "pass", headline: "Whole unit and clearance visible" },
      },
      {
        id: "shot_3_2",
        orderIndex: 1,
        title: "Model plate",
        shotType: "label",
        imageUrl: "https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?w=800&q=80",
        capturedAt: hoursAgo(31),
        feedback: {
          severity: "pass",
          headline: "Model and serial readable",
          checks: [
            { type: "label_detected", severity: "pass", label: "Label detected" },
            { type: "serial_detected", severity: "pass", label: "Serial detected" },
          ],
        },
      },
      {
        id: "shot_3_3",
        orderIndex: 2,
        title: "Vent connection",
        shotType: "close_up",
        imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
        capturedAt: hoursAgo(31),
        feedback: { severity: "pass", headline: "Vent is intact, no corrosion" },
      },
    ],
    customerAnswers: [
      { prompt: "How old is the unit?", answer: "About 11 years." },
      { prompt: "Any leaks or pooling water?", answer: "No, just slow recovery." },
    ],
    internalNotes: [],
    activity: [
      { id: "ev_3_1", type: "request_sent", label: "Request sent", actor: "Patrick", at: hoursAgo(48) },
      { id: "ev_3_2", type: "submission_received", label: "Submission received", actor: "Casey Wong", at: hoursAgo(30) },
      { id: "ev_3_3", type: "ai_review_completed", label: "AI review completed (readiness 100)", actor: "PhotoBrief AI", at: hoursAgo(30) },
      { id: "ev_3_4", type: "marked_reviewed", label: "Marked reviewed by Patrick", actor: "Patrick Owens", at: hoursAgo(28) },
    ],
  },
];

