-- Auto-generated seed of launch-ready global guide templates.
-- Idempotent: deletes existing global templates with the same names first.

DELETE FROM public.photo_guides WHERE is_global_template = true AND name IN ('Leak diagnosis intake','Water heater replacement','Junk removal quote','Landscaping site survey','Appliance repair intake','Move-in / move-out condition','Proof of completion','Insurance claim photo packet','Warranty claim intake','Return / RMA intake','Pest / wildlife report','Real estate listing shoot','Marketplace resale shoot','Used vehicle listing','Blank intake (you customize)','Universal 5-shot intake');

DO $$
DECLARE g_id UUID;
BEGIN

-- Guide: Leak diagnosis intake
INSERT INTO public.photo_guides (name, description, category, output_type, estimated_time_minutes, is_global_template, is_active)
VALUES ('Leak diagnosis intake', 'Capture the leak, surrounding area, and shut-off valve so we can quote accurately.', 'service_quote_intake'::topline_category, 'service_intake_brief'::output_type, 4, true, true) RETURNING id INTO g_id;
INSERT INTO public.guide_steps (guide_id, order_index, title, instruction, capture_type, overlay_type, ai_checks, required, allow_skip) VALUES (g_id, 0, 'Wide shot of the area', 'Stand back and capture the whole space around the leak.', 'photo'::capture_type, 'wide_scene'::overlay_type, ARRAY['blur','low_light','wide_shot_detected']::ai_check_type[], true, false);
INSERT INTO public.guide_steps (guide_id, order_index, title, instruction, capture_type, overlay_type, ai_checks, required, allow_skip) VALUES (g_id, 1, 'Close-up of the leak', 'Get close enough to see exactly where water is coming from.', 'photo'::capture_type, 'close_up'::overlay_type, ARRAY['blur','damage_visible','close_up_detected']::ai_check_type[], true, false);
INSERT INTO public.guide_steps (guide_id, order_index, title, instruction, capture_type, overlay_type, ai_checks, required, allow_skip) VALUES (g_id, 2, 'Shut-off valve', 'Photo of the nearest shut-off valve so we know what''s accessible.', 'photo'::capture_type, 'wide_scene'::overlay_type, ARRAY['blur','missing_required_item']::ai_check_type[], true, false);
INSERT INTO public.guide_steps (guide_id, order_index, title, instruction, capture_type, overlay_type, ai_checks, required, allow_skip) VALUES (g_id, 3, 'Supply line label', 'Straight-on photo of any label or stamp on the supply line.', 'label'::capture_type, 'document_label'::overlay_type, ARRAY['blur','unreadable_text','label_detected']::ai_check_type[], false, true);
INSERT INTO public.context_questions (guide_id, order_index, label, input_type, options, required) VALUES (g_id, 0, 'When did you first notice the leak?', 'short_text', NULL, true);
INSERT INTO public.context_questions (guide_id, order_index, label, input_type, options, required) VALUES (g_id, 1, 'Is water actively running right now?', 'single_select', '["Yes","No","Slow drip"]'::jsonb, true);

-- Guide: Water heater replacement
INSERT INTO public.photo_guides (name, description, category, output_type, estimated_time_minutes, is_global_template, is_active)
VALUES ('Water heater replacement', 'Photos of the unit, model plate, venting, and surrounding clearance.', 'service_quote_intake'::topline_category, 'service_intake_brief'::output_type, 3, true, true) RETURNING id INTO g_id;
INSERT INTO public.guide_steps (guide_id, order_index, title, instruction, capture_type, overlay_type, ai_checks, required, allow_skip) VALUES (g_id, 0, 'Full water heater', 'Capture the whole unit from a few feet back.', 'photo'::capture_type, 'wide_scene'::overlay_type, ARRAY['blur','wide_shot_detected']::ai_check_type[], true, false);
INSERT INTO public.guide_steps (guide_id, order_index, title, instruction, capture_type, overlay_type, ai_checks, required, allow_skip) VALUES (g_id, 1, 'Model & serial plate', 'Straight-on photo of the spec plate so model and serial are readable.', 'label'::capture_type, 'model_serial_plate'::overlay_type, ARRAY['blur','unreadable_text','serial_model_detected']::ai_check_type[], true, false);
INSERT INTO public.guide_steps (guide_id, order_index, title, instruction, capture_type, overlay_type, ai_checks, required, allow_skip) VALUES (g_id, 2, 'Venting', 'Show the vent pipe coming off the top of the unit.', 'photo'::capture_type, 'wide_scene'::overlay_type, ARRAY['blur']::ai_check_type[], true, false);
INSERT INTO public.context_questions (guide_id, order_index, label, input_type, options, required) VALUES (g_id, 0, 'How old is the current unit (approx)?', 'short_text', NULL, false);

-- Guide: Junk removal quote
INSERT INTO public.photo_guides (name, description, category, output_type, estimated_time_minutes, is_global_template, is_active)
VALUES ('Junk removal quote', 'Wide shots of the pile, access path, and any oversized items.', 'service_quote_intake'::topline_category, 'service_intake_brief'::output_type, 3, true, true) RETURNING id INTO g_id;
INSERT INTO public.guide_steps (guide_id, order_index, title, instruction, capture_type, overlay_type, ai_checks, required, allow_skip) VALUES (g_id, 0, 'Wide shot of the pile', 'Stand back so we can see the full size of the load.', 'photo'::capture_type, 'wide_scene'::overlay_type, ARRAY['blur','wide_shot_detected','missing_scale']::ai_check_type[], true, false);
INSERT INTO public.guide_steps (guide_id, order_index, title, instruction, capture_type, overlay_type, ai_checks, required, allow_skip) VALUES (g_id, 1, 'Access path', 'Show the path our crew will walk from the truck to the pile.', 'photo'::capture_type, 'wide_scene'::overlay_type, ARRAY['blur']::ai_check_type[], true, false);
INSERT INTO public.context_questions (guide_id, order_index, label, input_type, options, required) VALUES (g_id, 0, 'Any oversized items (mattress, couch, appliance)?', 'long_text', NULL, false);

-- Guide: Landscaping site survey
INSERT INTO public.photo_guides (name, description, category, output_type, estimated_time_minutes, is_global_template, is_active)
VALUES ('Landscaping site survey', 'Front yard, back yard, problem areas, and existing irrigation.', 'service_quote_intake'::topline_category, 'service_intake_brief'::output_type, 5, true, true) RETURNING id INTO g_id;
INSERT INTO public.guide_steps (guide_id, order_index, title, instruction, capture_type, overlay_type, ai_checks, required, allow_skip) VALUES (g_id, 0, 'Front yard wide shot', 'Capture the whole front yard from the street.', 'photo'::capture_type, 'wide_scene'::overlay_type, ARRAY['blur','wide_shot_detected']::ai_check_type[], true, false);
INSERT INTO public.guide_steps (guide_id, order_index, title, instruction, capture_type, overlay_type, ai_checks, required, allow_skip) VALUES (g_id, 1, 'Back yard wide shot', 'Capture the whole back yard from one corner.', 'photo'::capture_type, 'wide_scene'::overlay_type, ARRAY['blur','wide_shot_detected']::ai_check_type[], true, false);

-- Guide: Appliance repair intake
INSERT INTO public.photo_guides (name, description, category, output_type, estimated_time_minutes, is_global_template, is_active)
VALUES ('Appliance repair intake', 'Photos of the appliance, model plate, and the fault.', 'service_quote_intake'::topline_category, 'service_intake_brief'::output_type, 3, true, true) RETURNING id INTO g_id;
INSERT INTO public.guide_steps (guide_id, order_index, title, instruction, capture_type, overlay_type, ai_checks, required, allow_skip) VALUES (g_id, 0, 'Full appliance', 'Stand back so we can see the whole appliance.', 'photo'::capture_type, 'wide_scene'::overlay_type, ARRAY['blur']::ai_check_type[], true, false);
INSERT INTO public.guide_steps (guide_id, order_index, title, instruction, capture_type, overlay_type, ai_checks, required, allow_skip) VALUES (g_id, 1, 'Model plate', 'Straight-on shot of the model and serial plate.', 'label'::capture_type, 'model_serial_plate'::overlay_type, ARRAY['blur','unreadable_text','serial_model_detected']::ai_check_type[], true, false);

-- Guide: Move-in / move-out condition
INSERT INTO public.photo_guides (name, description, category, output_type, estimated_time_minutes, is_global_template, is_active)
VALUES ('Move-in / move-out condition', 'Room-by-room condition record with timestamps.', 'property_proof_records'::topline_category, 'proof_packet'::output_type, 8, true, true) RETURNING id INTO g_id;
INSERT INTO public.guide_steps (guide_id, order_index, title, instruction, capture_type, overlay_type, ai_checks, required, allow_skip) VALUES (g_id, 0, 'Living room — wide', 'Stand in one corner and capture the whole room.', 'photo'::capture_type, 'wide_scene'::overlay_type, ARRAY['blur','low_light','wide_shot_detected']::ai_check_type[], true, false);
INSERT INTO public.guide_steps (guide_id, order_index, title, instruction, capture_type, overlay_type, ai_checks, required, allow_skip) VALUES (g_id, 1, 'Kitchen — wide', 'Capture all cabinets and appliances in one frame.', 'photo'::capture_type, 'wide_scene'::overlay_type, ARRAY['blur','wide_shot_detected']::ai_check_type[], true, false);
INSERT INTO public.guide_steps (guide_id, order_index, title, instruction, capture_type, overlay_type, ai_checks, required, allow_skip) VALUES (g_id, 2, 'Bathroom — wide', 'Include the toilet, sink, and tub/shower.', 'photo'::capture_type, 'wide_scene'::overlay_type, ARRAY['blur','wide_shot_detected']::ai_check_type[], true, false);
INSERT INTO public.guide_steps (guide_id, order_index, title, instruction, capture_type, overlay_type, ai_checks, required, allow_skip) VALUES (g_id, 3, 'Bedroom — wide', 'Capture the full bedroom including closet doors.', 'photo'::capture_type, 'wide_scene'::overlay_type, ARRAY['blur','wide_shot_detected']::ai_check_type[], true, false);
INSERT INTO public.guide_steps (guide_id, order_index, title, instruction, capture_type, overlay_type, ai_checks, required, allow_skip) VALUES (g_id, 4, 'Existing damage close-ups', 'Close-up of any scuffs, stains, or damage you spot.', 'photo'::capture_type, 'close_up'::overlay_type, ARRAY['blur','damage_visible','close_up_detected']::ai_check_type[], false, true);
INSERT INTO public.context_questions (guide_id, order_index, label, input_type, options, required) VALUES (g_id, 0, 'Is this a move-in or move-out walkthrough?', 'single_select', '["Move-in","Move-out"]'::jsonb, true);

-- Guide: Proof of completion
INSERT INTO public.photo_guides (name, description, category, output_type, estimated_time_minutes, is_global_template, is_active)
VALUES ('Proof of completion', 'Before / after shots that double as the customer receipt.', 'property_proof_records'::topline_category, 'proof_packet'::output_type, 2, true, true) RETURNING id INTO g_id;
INSERT INTO public.guide_steps (guide_id, order_index, title, instruction, capture_type, overlay_type, ai_checks, required, allow_skip) VALUES (g_id, 0, 'Before shot', 'Wide shot of the area before work started.', 'photo'::capture_type, 'before_after_alignment'::overlay_type, ARRAY['blur','wide_shot_detected']::ai_check_type[], true, false);
INSERT INTO public.guide_steps (guide_id, order_index, title, instruction, capture_type, overlay_type, ai_checks, required, allow_skip) VALUES (g_id, 1, 'After shot — same angle', 'Same angle and framing as the before photo.', 'photo'::capture_type, 'before_after_alignment'::overlay_type, ARRAY['blur','wide_shot_detected']::ai_check_type[], true, false);
INSERT INTO public.guide_steps (guide_id, order_index, title, instruction, capture_type, overlay_type, ai_checks, required, allow_skip) VALUES (g_id, 2, 'Receipt / invoice (optional)', 'Photo of the receipt or invoice if applicable.', 'document'::capture_type, 'document_label'::overlay_type, ARRAY['blur','unreadable_text','receipt_order_detected']::ai_check_type[], false, true);

-- Guide: Insurance claim photo packet
INSERT INTO public.photo_guides (name, description, category, output_type, estimated_time_minutes, is_global_template, is_active)
VALUES ('Insurance claim photo packet', 'Damage overview, close-ups, and supporting documents.', 'property_proof_records'::topline_category, 'proof_packet'::output_type, 6, true, true) RETURNING id INTO g_id;
INSERT INTO public.guide_steps (guide_id, order_index, title, instruction, capture_type, overlay_type, ai_checks, required, allow_skip) VALUES (g_id, 0, 'Wide shot of the damaged area', 'Capture the whole damaged area in context.', 'photo'::capture_type, 'wide_scene'::overlay_type, ARRAY['blur','wide_shot_detected']::ai_check_type[], true, false);
INSERT INTO public.guide_steps (guide_id, order_index, title, instruction, capture_type, overlay_type, ai_checks, required, allow_skip) VALUES (g_id, 1, 'Close-up of the damage', 'Get close enough to see the extent of the damage.', 'photo'::capture_type, 'close_up'::overlay_type, ARRAY['blur','damage_visible','close_up_detected']::ai_check_type[], true, false);
INSERT INTO public.guide_steps (guide_id, order_index, title, instruction, capture_type, overlay_type, ai_checks, required, allow_skip) VALUES (g_id, 2, 'Reference object for scale', 'Place a coin, ruler, or hand near the damage for scale.', 'photo'::capture_type, 'scale_reference'::overlay_type, ARRAY['missing_scale','close_up_detected']::ai_check_type[], true, false);
INSERT INTO public.guide_steps (guide_id, order_index, title, instruction, capture_type, overlay_type, ai_checks, required, allow_skip) VALUES (g_id, 3, 'Receipt / proof of ownership', 'Photo of any receipt, invoice, or registration.', 'document'::capture_type, 'document_label'::overlay_type, ARRAY['blur','unreadable_text','receipt_order_detected']::ai_check_type[], false, true);
INSERT INTO public.context_questions (guide_id, order_index, label, input_type, options, required) VALUES (g_id, 0, 'Date the damage occurred', 'short_text', NULL, true);
INSERT INTO public.context_questions (guide_id, order_index, label, input_type, options, required) VALUES (g_id, 1, 'Brief description of what happened', 'long_text', NULL, true);

-- Guide: Warranty claim intake
INSERT INTO public.photo_guides (name, description, category, output_type, estimated_time_minutes, is_global_template, is_active)
VALUES ('Warranty claim intake', 'Product, serial, and the issue — everything support needs.', 'product_support_claims'::topline_category, 'claim_packet'::output_type, 4, true, true) RETURNING id INTO g_id;
INSERT INTO public.guide_steps (guide_id, order_index, title, instruction, capture_type, overlay_type, ai_checks, required, allow_skip) VALUES (g_id, 0, 'Whole product', 'Photo of the whole product on a clean surface.', 'photo'::capture_type, 'wide_scene'::overlay_type, ARRAY['blur','wide_shot_detected']::ai_check_type[], true, false);
INSERT INTO public.guide_steps (guide_id, order_index, title, instruction, capture_type, overlay_type, ai_checks, required, allow_skip) VALUES (g_id, 1, 'Serial number', 'Close-up of the serial number / model label.', 'label'::capture_type, 'model_serial_plate'::overlay_type, ARRAY['blur','unreadable_text','serial_model_detected']::ai_check_type[], true, false);
INSERT INTO public.guide_steps (guide_id, order_index, title, instruction, capture_type, overlay_type, ai_checks, required, allow_skip) VALUES (g_id, 2, 'The issue', 'Close-up showing the defect or damage.', 'photo'::capture_type, 'close_up'::overlay_type, ARRAY['blur','damage_visible','close_up_detected']::ai_check_type[], true, false);
INSERT INTO public.guide_steps (guide_id, order_index, title, instruction, capture_type, overlay_type, ai_checks, required, allow_skip) VALUES (g_id, 3, 'Receipt or proof of purchase', 'Photo of the receipt or order confirmation.', 'document'::capture_type, 'document_label'::overlay_type, ARRAY['blur','unreadable_text','receipt_order_detected']::ai_check_type[], true, false);
INSERT INTO public.context_questions (guide_id, order_index, label, input_type, options, required) VALUES (g_id, 0, 'What''s wrong with the product?', 'long_text', NULL, true);

-- Guide: Return / RMA intake
INSERT INTO public.photo_guides (name, description, category, output_type, estimated_time_minutes, is_global_template, is_active)
VALUES ('Return / RMA intake', 'Confirm what shipped, the condition, and packaging.', 'product_support_claims'::topline_category, 'claim_packet'::output_type, 3, true, true) RETURNING id INTO g_id;
INSERT INTO public.guide_steps (guide_id, order_index, title, instruction, capture_type, overlay_type, ai_checks, required, allow_skip) VALUES (g_id, 0, 'Item as received', 'Photo of the item still in the original packaging.', 'photo'::capture_type, 'wide_scene'::overlay_type, ARRAY['blur']::ai_check_type[], true, false);
INSERT INTO public.guide_steps (guide_id, order_index, title, instruction, capture_type, overlay_type, ai_checks, required, allow_skip) VALUES (g_id, 1, 'Issue close-up', 'Close-up of the defect or wrong item.', 'photo'::capture_type, 'close_up'::overlay_type, ARRAY['blur','damage_visible','close_up_detected']::ai_check_type[], true, false);
INSERT INTO public.guide_steps (guide_id, order_index, title, instruction, capture_type, overlay_type, ai_checks, required, allow_skip) VALUES (g_id, 2, 'Packing slip', 'Photo of the packing slip or order number.', 'document'::capture_type, 'document_label'::overlay_type, ARRAY['unreadable_text','receipt_order_detected']::ai_check_type[], true, false);
INSERT INTO public.context_questions (guide_id, order_index, label, input_type, options, required) VALUES (g_id, 0, 'Reason for the return', 'single_select', '["Defective","Wrong item","Doesn''t fit","Changed my mind","Other"]'::jsonb, true);

-- Guide: Pest / wildlife report
INSERT INTO public.photo_guides (name, description, category, output_type, estimated_time_minutes, is_global_template, is_active)
VALUES ('Pest / wildlife report', 'Photos and short context for safe identification.', 'product_support_claims'::topline_category, 'claim_packet'::output_type, 3, true, true) RETURNING id INTO g_id;
INSERT INTO public.guide_steps (guide_id, order_index, title, instruction, capture_type, overlay_type, ai_checks, required, allow_skip) VALUES (g_id, 0, 'Where you saw it', 'Wide shot of the area where you noticed activity.', 'photo'::capture_type, 'wide_scene'::overlay_type, ARRAY['blur']::ai_check_type[], true, false);
INSERT INTO public.guide_steps (guide_id, order_index, title, instruction, capture_type, overlay_type, ai_checks, required, allow_skip) VALUES (g_id, 1, 'Close-up (from a safe distance)', 'Zoom in if you can do so safely. Don''t get close to the animal.', 'photo'::capture_type, 'close_up'::overlay_type, ARRAY['blur','unsafe_condition_flag']::ai_check_type[], false, true);
INSERT INTO public.context_questions (guide_id, order_index, label, input_type, options, required) VALUES (g_id, 0, 'When did you last see activity?', 'short_text', NULL, true);

-- Guide: Real estate listing shoot
INSERT INTO public.photo_guides (name, description, category, output_type, estimated_time_minutes, is_global_template, is_active)
VALUES ('Real estate listing shoot', 'Listing-quality photos of every key room and exterior.', 'sales_marketing_content'::topline_category, 'listing_draft'::output_type, 10, true, true) RETURNING id INTO g_id;
INSERT INTO public.guide_steps (guide_id, order_index, title, instruction, capture_type, overlay_type, ai_checks, required, allow_skip) VALUES (g_id, 0, 'Front exterior', 'Stand across the street and capture the whole front of the home.', 'photo'::capture_type, 'wide_scene'::overlay_type, ARRAY['blur','wide_shot_detected']::ai_check_type[], true, false);
INSERT INTO public.guide_steps (guide_id, order_index, title, instruction, capture_type, overlay_type, ai_checks, required, allow_skip) VALUES (g_id, 1, 'Living room', 'Stand in one corner so all furniture is in frame.', 'photo'::capture_type, 'wide_scene'::overlay_type, ARRAY['blur','low_light','wide_shot_detected']::ai_check_type[], true, false);
INSERT INTO public.guide_steps (guide_id, order_index, title, instruction, capture_type, overlay_type, ai_checks, required, allow_skip) VALUES (g_id, 2, 'Kitchen', 'Capture cabinets, counters, and appliances together.', 'photo'::capture_type, 'wide_scene'::overlay_type, ARRAY['blur','low_light','wide_shot_detected']::ai_check_type[], true, false);
INSERT INTO public.guide_steps (guide_id, order_index, title, instruction, capture_type, overlay_type, ai_checks, required, allow_skip) VALUES (g_id, 3, 'Primary bedroom', 'Capture the bed and as much of the room as possible.', 'photo'::capture_type, 'wide_scene'::overlay_type, ARRAY['blur','wide_shot_detected']::ai_check_type[], true, false);
INSERT INTO public.guide_steps (guide_id, order_index, title, instruction, capture_type, overlay_type, ai_checks, required, allow_skip) VALUES (g_id, 4, 'Backyard', 'Stand at the back door and capture the whole yard.', 'photo'::capture_type, 'wide_scene'::overlay_type, ARRAY['blur','wide_shot_detected']::ai_check_type[], true, false);
INSERT INTO public.context_questions (guide_id, order_index, label, input_type, options, required) VALUES (g_id, 0, 'Anything you want highlighted in the listing?', 'long_text', NULL, false);

-- Guide: Marketplace resale shoot
INSERT INTO public.photo_guides (name, description, category, output_type, estimated_time_minutes, is_global_template, is_active)
VALUES ('Marketplace resale shoot', 'Studio-style photos for Facebook Marketplace, eBay, etc.', 'sales_marketing_content'::topline_category, 'listing_draft'::output_type, 4, true, true) RETURNING id INTO g_id;
INSERT INTO public.guide_steps (guide_id, order_index, title, instruction, capture_type, overlay_type, ai_checks, required, allow_skip) VALUES (g_id, 0, 'Hero shot — whole item', 'Place on a clean background and capture the whole item.', 'photo'::capture_type, 'wide_scene'::overlay_type, ARRAY['blur','wide_shot_detected']::ai_check_type[], true, false);
INSERT INTO public.guide_steps (guide_id, order_index, title, instruction, capture_type, overlay_type, ai_checks, required, allow_skip) VALUES (g_id, 1, 'Brand or model label', 'Close-up of the label or logo.', 'label'::capture_type, 'document_label'::overlay_type, ARRAY['blur','unreadable_text','label_detected']::ai_check_type[], true, false);
INSERT INTO public.guide_steps (guide_id, order_index, title, instruction, capture_type, overlay_type, ai_checks, required, allow_skip) VALUES (g_id, 2, 'Any flaws (be honest!)', 'Close-up of any wear, scratches, or imperfections.', 'photo'::capture_type, 'close_up'::overlay_type, ARRAY['blur','damage_visible','close_up_detected']::ai_check_type[], false, true);
INSERT INTO public.context_questions (guide_id, order_index, label, input_type, options, required) VALUES (g_id, 0, 'Asking price', 'number', NULL, false);

-- Guide: Used vehicle listing
INSERT INTO public.photo_guides (name, description, category, output_type, estimated_time_minutes, is_global_template, is_active)
VALUES ('Used vehicle listing', 'Exterior, interior, dash, and VIN — everything a buyer asks for.', 'sales_marketing_content'::topline_category, 'listing_draft'::output_type, 6, true, true) RETURNING id INTO g_id;
INSERT INTO public.guide_steps (guide_id, order_index, title, instruction, capture_type, overlay_type, ai_checks, required, allow_skip) VALUES (g_id, 0, '3/4 front exterior', 'Stand at the front-left corner and capture the whole car.', 'photo'::capture_type, 'wide_scene'::overlay_type, ARRAY['blur','wide_shot_detected']::ai_check_type[], true, false);
INSERT INTO public.guide_steps (guide_id, order_index, title, instruction, capture_type, overlay_type, ai_checks, required, allow_skip) VALUES (g_id, 1, '3/4 rear exterior', 'Stand at the rear-right corner and capture the whole car.', 'photo'::capture_type, 'wide_scene'::overlay_type, ARRAY['blur','wide_shot_detected']::ai_check_type[], true, false);
INSERT INTO public.guide_steps (guide_id, order_index, title, instruction, capture_type, overlay_type, ai_checks, required, allow_skip) VALUES (g_id, 2, 'Dashboard with mileage', 'Photo of the dash showing odometer reading.', 'photo'::capture_type, 'close_up'::overlay_type, ARRAY['blur','unreadable_text','close_up_detected']::ai_check_type[], true, false);
INSERT INTO public.guide_steps (guide_id, order_index, title, instruction, capture_type, overlay_type, ai_checks, required, allow_skip) VALUES (g_id, 3, 'Interior — front seats', 'Open the door and capture the front seats and dash.', 'photo'::capture_type, 'wide_scene'::overlay_type, ARRAY['blur','low_light']::ai_check_type[], true, false);
INSERT INTO public.guide_steps (guide_id, order_index, title, instruction, capture_type, overlay_type, ai_checks, required, allow_skip) VALUES (g_id, 4, 'VIN plate', 'Close-up of the VIN at the base of the windshield.', 'label'::capture_type, 'model_serial_plate'::overlay_type, ARRAY['blur','unreadable_text','serial_model_detected']::ai_check_type[], true, false);
INSERT INTO public.context_questions (guide_id, order_index, label, input_type, options, required) VALUES (g_id, 0, 'Any known issues we should mention?', 'long_text', NULL, false);

-- Guide: Blank intake (you customize)
INSERT INTO public.photo_guides (name, description, category, output_type, estimated_time_minutes, is_global_template, is_active)
VALUES ('Blank intake (you customize)', 'A near-empty starting point — name it, add steps, send.', 'custom_business_intake'::topline_category, 'custom_brief'::output_type, 2, true, true) RETURNING id INTO g_id;
INSERT INTO public.guide_steps (guide_id, order_index, title, instruction, capture_type, overlay_type, ai_checks, required, allow_skip) VALUES (g_id, 0, 'Wide shot', 'Stand back and capture the whole subject.', 'photo'::capture_type, 'wide_scene'::overlay_type, ARRAY['blur','wide_shot_detected']::ai_check_type[], true, false);
INSERT INTO public.guide_steps (guide_id, order_index, title, instruction, capture_type, overlay_type, ai_checks, required, allow_skip) VALUES (g_id, 1, 'Close-up', 'Get close on the most important detail.', 'photo'::capture_type, 'close_up'::overlay_type, ARRAY['blur','close_up_detected']::ai_check_type[], false, true);
INSERT INTO public.context_questions (guide_id, order_index, label, input_type, options, required) VALUES (g_id, 0, 'Any extra context for our team?', 'long_text', NULL, false);

-- Guide: Universal 5-shot intake
INSERT INTO public.photo_guides (name, description, category, output_type, estimated_time_minutes, is_global_template, is_active)
VALUES ('Universal 5-shot intake', 'Wide, close-up, label, scale reference, and a free-form context shot.', 'custom_business_intake'::topline_category, 'custom_brief'::output_type, 5, true, true) RETURNING id INTO g_id;
INSERT INTO public.guide_steps (guide_id, order_index, title, instruction, capture_type, overlay_type, ai_checks, required, allow_skip) VALUES (g_id, 0, 'Wide shot', 'Capture the full subject in context.', 'photo'::capture_type, 'wide_scene'::overlay_type, ARRAY['blur','wide_shot_detected']::ai_check_type[], true, false);
INSERT INTO public.guide_steps (guide_id, order_index, title, instruction, capture_type, overlay_type, ai_checks, required, allow_skip) VALUES (g_id, 1, 'Close-up', 'Zoom in on the most important detail.', 'photo'::capture_type, 'close_up'::overlay_type, ARRAY['blur','close_up_detected']::ai_check_type[], true, false);
INSERT INTO public.guide_steps (guide_id, order_index, title, instruction, capture_type, overlay_type, ai_checks, required, allow_skip) VALUES (g_id, 2, 'Any label or model number', 'Straight-on shot of any label or stamp.', 'label'::capture_type, 'document_label'::overlay_type, ARRAY['blur','unreadable_text','label_detected']::ai_check_type[], false, true);
INSERT INTO public.guide_steps (guide_id, order_index, title, instruction, capture_type, overlay_type, ai_checks, required, allow_skip) VALUES (g_id, 3, 'Scale reference', 'Place a hand, coin, or ruler in the shot for scale.', 'photo'::capture_type, 'scale_reference'::overlay_type, ARRAY['missing_scale','close_up_detected']::ai_check_type[], false, true);
INSERT INTO public.guide_steps (guide_id, order_index, title, instruction, capture_type, overlay_type, ai_checks, required, allow_skip) VALUES (g_id, 4, 'Anything else worth showing?', 'One extra shot — your call.', 'photo'::capture_type, 'wide_scene'::overlay_type, ARRAY['blur']::ai_check_type[], false, true);
INSERT INTO public.context_questions (guide_id, order_index, label, input_type, options, required) VALUES (g_id, 0, 'What is this for?', 'short_text', NULL, false);
END $$;